ALTER TABLE "cadets" ADD COLUMN "menstrual_frequency" varchar(20);--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "menstrual_days" integer;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "last_menstrual_date" timestamp;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "menstrual_aids" text;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "sexually_active" varchar(10);--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "marital_status" varchar(20);--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "pregnancy_history" text;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "contraceptive_history" text;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "surgery_history" text;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "medical_condition" text;--> statement-breakpoint
ALTER TABLE "cadets" ADD COLUMN "hemoglobin_level" numeric(4, 2);